/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   "introduction",
  //   {
  //     "Getting Started": [
  //       "getting-started",
  //       "basic-concepts",
  //       "using-flatpak",
  //       "first-build",
  //     ],
  //   },
  //   {
  //     Building: [
  //       "building",
  //       "conventions",
  //       "dependencies",
  //       "flatpak-builder",
  //       "manifests",
  //       "sandbox-permissions",
  //       "guides",
  //     ],
  //   },
  //   "debugging",
  //   {
  //     Publishing: [
  //       "publishing",
  //       "hosting-a-repository",
  //       "single-file-bundles",
  //       "usb-drives",
  //     ],
  //   },
  //   "desktop-integration",
  //   "tips-and-tricks",
  // ],
};

module.exports = sidebars;
