name: Deploy

on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      # 6.0.2
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          # Needed for sitemap generation with valid lastmod
          # https://github.com/facebook/docusaurus/pull/9954#issuecomment-2032900942
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js
        # 6.4.0
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: "20"
          package-manager-cache: false

      - name: Setup Pages
        # 6.0.0
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache yarn
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-deploy-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-deploy-

      - name: Install dependencies
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Build website
        run: yarn build

      - name: Upload artifact
        # 5.0.0
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9
        with:
          path: ./build

  deploy:
    needs:
      - build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # 5.0.0
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128
